language: python
sudo: false

python:
    - "3.4"

before_install:
    - apt-get update -qq
    - apt-get install -qq -y build-essential ftp golang unzip
      bwa tabix seqtk libwww-perl
    - ./install-dependencies.sh
    # Install conda only if necessary
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        command -v conda >/dev/null || { wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda; }
      else
        command -v conda >/dev/null || { wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda; }
      fi
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda
    # Useful for debugging any issues with conda
    - conda info -a
    # install deps from environment.yml and activate
    - conda env create -q python=$TRAVIS_PYTHON_VERSION
    - source activate test-virmet
    - python -m coverage --version
    - pip$TRAVIS_PYTHON_VERSION install codecov
    - ln -sv /bin/uname /usr/bin/uname
    - export PATH=/usr/local/bin:$PATH

script:
    - coverage run -m unittest

after_success:
    - codecov
