before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y build-essential ncurses-dev git cmake ncbi-blast+

install: ./install-dependencies.sh

after_install:
    - export PATH=$PATH:$PWD/edirect/
    - ln -sv PATH=$PATH:$PWD/prinseq-lite-0.20.4/prinseq-lite.pl /usr/local/bin/prinseq-lite.pl
    - export PATH=$PATH:$PWD/STAR-STAR_2.4.2a/source

script:
    - true
