language: python
python:
    - "3.4"

before_install:
    - sudo add-apt-repository universe
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y build-essential ncurses-dev git ncbi-blast+ cmake unzip bwa tabix python3-pandas python3-numpy python3-scipy python3-biopython

install:
    - ./install-dependencies.sh
    - pip install nose2

after_install:
    - export PATH=$PATH:/tmp/edirect
    - sudo ln -sv PATH=$PATH:tmp/prinseq-lite-0.20.4/prinseq-lite.pl /usr/local/bin/prinseq-lite.pl
    - export PATH=/usr/local/bin:$PATH

script:
    - python -m unittest
