sudo: required
dist: trusty
language: python
python:
    - "3.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y build-essential ncurses-dev git cmake unzip
      libblas-dev liblapack-dev gfortran bwa tabix ncbi-blast+ libwww-perl

install:
    - ./install-dependencies.sh
    - pip install -r requirements.txt

after_install:
    - export PATH=$PATH:/tmp/edirect
    - sudo ln -sv PATH=$PATH:tmp/prinseq-lite-0.20.4/prinseq-lite.pl /usr/local/bin/prinseq-lite.pl
    - export PATH=/usr/local/bin:$PATH

script:
    - python -m unittest
