language: python
sudo: false

python:
    - "3.4"

addons:
  apt:
    packages:
    - build-essential
    - ftp
    - golang
    - unzip
    - bwa
    - tabix
    - seqtk
    - libwww-perl

cache:
  directories:
  - $HOME/samtools-1.3
  - $HOME/edirect
  - $HOME/prinseq
  - $HOME/ncbi-blast-2.3.0+
  - $HOME/miniconda

before_install:
    - ./install-dependencies.sh

    # Install conda only if necessary
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [ ! -d "$HOME/miniconda/" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda;
      else
        echo "Using cached conda";
      fi
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update conda
    # Useful for debugging any issues with conda
    - conda info -a
    # install deps from environment.yml and activate
    - conda env create -q python=$TRAVIS_PYTHON_VERSION
    - source activate test-virmet
    - python -m coverage --version
    - pip$TRAVIS_PYTHON_VERSION install codecov

    - export PATH=$PATH:$HOME/edirect
    - export PATH=$PATH:$HOME/prinseq
    - export PATH=$PATH:$HOME/samtools-1.3
    - export PATH=$PATH:$HOME/ncbi-blast-2.3.0+/bin

script:
    - ls -R $HOME/miniconda
    - coverage run -m unittest

after_success:
    - codecov
