sudo: required
dist: trusty
language: python
python:
    - "3.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y build-essential ncurses-dev git cmake unzip
      libblas-dev liblapack-dev gfortran bwa tabix ncbi-blast+ libwww-perl

install:
    - ./install-dependencies.sh
    # Install conda
    - sudo pip install conda==3.17.0
    # install deps
    - sudo conda init
    - sudo conda update conda --yes
    - deps='pip numpy pandas'
    - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"

after_install:
    - export PATH=$HOME/py/bin:$PATH
    - export PATH=$PATH:/tmp/edirect
    - sudo ln -sv PATH=$PATH:tmp/prinseq-lite-0.20.4/prinseq-lite.pl /usr/local/bin/prinseq-lite.pl
    - export PATH=/usr/local/bin:$PATH

script:
    - python -m unittest
