language: python

sudo: false

python:
    - "3.4"

addons:
  apt:
    packages:
    - build-essential
    - ftp
    - unzip
    - bwa
    - libwww-perl
    - seqtk


cache:
  directories:
  - $HOME/samtools-1.3
  - $HOME/edirect
  - $HOME/prinseq
  - $HOME/ncbi-blast-2.3.0+

before_install:
    - ./install-dependencies.sh

    # Install conda only if necessary
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # install deps from environment.yml and activate
    - conda env create -q python=$TRAVIS_PYTHON_VERSION
    - source activate test-virmet
    - conda list
    - python -m coverage --version
    - pip$TRAVIS_PYTHON_VERSION install codecov

    - export PATH=$PATH:$HOME/edirect
    - export PATH=$PATH:$HOME/prinseq
    - export PATH=$PATH:$HOME/samtools-1.3
    - export PATH=$PATH:$HOME/ncbi-blast-2.3.0+/bin

script:
    - coverage run -m unittest

after_success:
    - codecov
