sudo: required
dist: trusty
language: python
python:
    - "3.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y build-essential ncurses-dev git cmake unzip
      libblas-dev liblapack-dev gfortran bwa tabix ncbi-blast+ libwww-perl

install:
    #- ./install-dependencies.sh

    # Install conda
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    # Useful for debugging any issues with conda
    - conda info -a
    # install deps and activate
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pandas
    - source activate test-environment

after_install:
    - export PATH=$HOME/py/bin:$PATH
    - export PATH=$PATH:/tmp/edirect
    - sudo ln -sv PATH=$PATH:tmp/prinseq-lite-0.20.4/prinseq-lite.pl /usr/local/bin/prinseq-lite.pl
    - export PATH=/usr/local/bin:$PATH

script:
    - python -m unittest
