before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq -y build-essential ncurses-dev git cmake ncbi-blast+

install: ./install-dependencies.sh

after_install:
    - export PATH=$PATH:$PWD/edirect/

script:
    - true
