sudo: required

language: python

services:
    - docker

before_install:
- docker pull ozagordi/virmet
- docker run ozagordi/virmet /bin/sh -c "cd /opt/VirMet; coverage run -m unittest;"
- docker ps -a

script:
- coverage run -m unittest

#after_success:
#    - codecov
